(import_b_keyword) @keyword  
(const_keyword) @keyword 
(case_keyword) @keyword
(enum_keyword) @keyword
(break_keyword) @keyword
(default_keyword) @keyword
(match_keyword) @keyword
(else_keyword) @keyword
(elseif_keyword) @keyword
(struct_keyword) @keyword
(have_keyword) @keyword
(auto_keyword) @keyword
(fn_keyword) @keyword 
(if_keyword) @keyword
(return_keyword) @keyword
(loop_keyword) @keyword

(identifier_fn) @function
(call_b_keyword) @function.macro 
(built_in_funcs) @function.macro 

(escape_sequence) @string.escape 
(double_quoted_string) @string
(single_quoted_string) @character

(popen) @punctuation.bracket
(pclose) @punctuation.bracket
(bopen) @punctuation.bracket
(bclose) @punctuation.bracket
(bropen) @punctuation.bracket
(brclose) @punctuation.bracket
(arrow_open) @punctuation.bracket
(arrow_close) @punctuation.bracket
(dot) @punctuation.bracket
(semi) @punctuation.delimiter
(colon) @punctuation.delimiter
(comma) @punctuation.delimiter

(unary_ops) @operator
(bin_operators) @operator
(bang_t) @operator
(ques_t) @operator
(mul_op) @operator
(eq_op) @operator
(walrus_op) @operator 
(pree_ops) @operator
(arrow_point) @operator
(and) @operator
(number) @number
(comment) @comment
(identifier) @module
(identifier_c) @constant 
(identifier_sp) @property
(identifier_t) @type
